name: prod-build

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Prod pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.3'
      - name: Setup CI/CD Server
        run: |
          sudo apt-get update &&
          sudo apt install zip
      - name: Install Composer Dependencies
        run: |
          composer self-update --1
          composer install
      - name: Run Scripts
        run: |
          chmod +x scripts/create_dotenv.sh
          scripts/create_dotenv.sh
        env:
          APP_NAME: ${{secrets.APP_NAME}}
          APP_ENV: ${{secrets.APP_ENV}}
          APP_KEY: ${{secrets.APP_KEY}}
          APP_DEBUG: ${{secrets.APP_DEBUG}}
          APP_LOG_LEVEL: ${{secrets.APP_LOG_LEVEL}}
          APP_LOG: ${{secrets.APP_LOG}}
          APP_URL: ${{secrets.APP_URL}}
          DB_CONNECTION: ${{secrets.DB_CONNECTION}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_DATABASE: ${{secrets.DB_DATABASE}}
          DB_USERNAME: ${{secrets.DB_USERNAME}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      - name: Compress app
        run: zip -r sponsorship-${GITHUB_SHA}.zip .
